### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ayoahha** [RohitKushvaha01/Xed-Editor#100]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1724598633773
LocalTime : 25 août 2024 17:10:33

ALL_CODENAMES = [REL]
ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = Pixel 6
MIN_SUPPORTED_TARGET_SDK_INT = 28
RESOURCES_SDK_INT = 34
SECURITY_PATCH = 2024-08-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 31
CODENAME = REL
manufacturer = Google
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
DEVICE_INITIAL_SDK_INT = 31
PREVIEW_SDK_INT = 0
SDK = 34
brand = google
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 2024082200

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
Error Cause : java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
	at com.rk.xededitor.setupEditor.setupLanguage(Unknown Source:2)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.java:237)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.java:117)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 15 more

**Comment by ayoahha** [comment]
Hi
I tried to open a xlsx document from my nextcloud instance and this error appeared. First time, never see this

May you take a look please ?

**Comment by ayoahha** [comment]
> 
> try this latest commit artifact https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10556997076

Sorry, how can i suppose to do that exactly ?
This commit is not published yet within the nextcloud app/core thing, isn't it ?

**Comment by RohitKushvaha01** [comment]
> > try this latest commit artifact https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10556997076
> 
> Sorry, how can i suppose to do that exactly ? This commit is not published yet within the nextcloud app/core thing, isn't it ?

scroll down to Artifacts section and download the apk file

 https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10557344894#artifacts

**Comment by ayoahha** [comment]
> > 
> > Sorry, how can i suppose to do that exactly ? This commit is not published yet within the nextcloud app/core thing

This is not an app (that i can launch as is), this is a module within a nextcloud so i do not know exactly how to do !

**Comment by RohitKushvaha01** [comment]
> > > 
> > > Sorry, how can i suppose to do that exactly ? This commit is not published yet within the nextcloud app/core thing
> 
> This is not an app (that i can launch as is), this is a module within a nextcloud so i do not know exactly how to do !

https://github.com/user-attachments/assets/0ebbc937-4d3e-4c2d-a8b3-6f6186fa757b

After downloading the zip file
Unzip it and install the Karbon.apk 

This app has nothing to do with nextcloud
