### ISSUE TITLE
Crash Report: Loading plugins from repo

### ISSUE THREAD

**Issue by Brajesh3** [RohitKushvaha01/Xed-Editor#144]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-2'
Unix Time : 1726734625560
LocalTime : 19 Sept 2024 14:00:25

ACTIVE_CODENAMES = []
app_version = 2.7.1
device_model = SM-M115F
SEM_INT = 3101
SECURITY_PATCH = 2023-11-01
BASE_OS = samsung/m11qnnxx/m11q:12/SP1A.210812.016/M115FXXU5CWE3:user/release-keys
SEM_FIRST_SDK_INT = 29
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
SEM_PLATFORM_INT = 130100
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = M115FXXS5CWK3

Error Message : Only the original thread that created a view hierarchy can touch its views.
Error Cause : null
Error StackTrace : 

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11177)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2482)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.widget.ScrollView.requestLayout(ScrollView.java:2577)
	at android.view.View.requestLayout(View.java:27053)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:5582)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5557)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12278)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:7498)
	at androidx.recyclerview.widget.AdapterListUpdateCallback.onInserted(AdapterListUpdateCallback.java:42)
	at androidx.recyclerview.widget.AsyncListDiffer.submitList(AsyncListDiffer.java:283)
	at androidx.recyclerview.widget.AsyncListDiffer.submitList(AsyncListDiffer.java:231)
	at androidx.recyclerview.widget.ListAdapter.submitList(ListAdapter.java:128)
	at com.rk.xededitor.PluginClient.ActivityPluginRepo.onCreate$lambda$2(ActivityPluginRepo.kt:80)
	at com.rk.xededitor.PluginClient.ActivityPluginRepo.$r8$lambda$Cc44GtonDAmcw5EhGFbGmN5fMbI(Unknown Source:0)
	at com.rk.xededitor.PluginClient.ActivityPluginRepo$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
	at com.rk.xededitor.PluginClient.RepoManager$getPluginsCallback$1$1.invokeSuspend(RepoManager.kt:109)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b6ad58d, Dispatchers.IO]

**Comment by AndroMaster436** [comment]
Clone of #143
