### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by PolcioHubi** [RohitKushvaha01/Xed-Editor#171]
Fatal Crash occurred on Thread named 'Thread-95'
Unix Time : 1727822097019
LocalTime : 2 paź 2024 00:34:57

ACTIVE_CODENAMES = []
app_version = 2.3.0
device_model = SM-S926B
SEM_INT = 3402
SECURITY_PATCH = 2024-08-01
BASE_OS = 
SEM_FIRST_SDK_INT = 34
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150500
brand = samsung
supported_abi = [arm64-v8a]
INCREMENTAL = S926BXXU3AXH7

Error Message : Failed to allocate a 150292120 byte allocation with 4120976 free bytes and 4024KB until OOM, target footprint 268435456, growth limit 268435456
Error Cause : null
Error StackTrace : 

java.lang.OutOfMemoryError: Failed to allocate a 150292120 byte allocation with 4120976 free bytes and 4024KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
	at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233)
	at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1685)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:692)
	at java.lang.StringBuilder.append(StringBuilder.java:242)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Unknown Source:38)
	at io.github.rosemoe.sora.text.Content.toString(Unknown Source:0)
	at com.rk.xededitor.MainActivity.DynamicFragment$$ExternalSyntheticLambda2.run(Unknown Source:47)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by RohitKushvaha01** [comment]
@PolcioHubi You are using a very old version
