### ISSUE TITLE
Crash Report: Error when click on Editor at Settings

### ISSUE THREAD

**Issue by marcosnitola** [RohitKushvaha01/Xed-Editor#176]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728095082077
LocalTime : 4/10/2024 21:24:42

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = moto e32
SECURITY_PATCH = 2024-02-05
BASE_OS = motorola/hawaii/hawaii:11/ROR31.335-58/c1989:user/release-keys
RELEASE = 11
CODENAME = REL
manufacturer = motorola
RELEASE_OR_CODENAME = 11
SDK_INT = 30
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 30
brand = motorola
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 612c2

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7955)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at de.Maxr1998.modernpreferences.Preference.getBoolean(Preferences.kt:321)
	at de.Maxr1998.modernpreferences.preferences.TwoStatePreference.onAttach$libsettings_release(TwoStatePreference.kt:58)
	at de.Maxr1998.modernpreferences.Preference.attachToScreen$libsettings_release(Preferences.kt:166)
	at de.Maxr1998.modernpreferences.PreferenceScreen.<init>(Preferences.kt:433)
	at de.Maxr1998.modernpreferences.PreferenceScreen.<init>(Unknown Source:0)
	at de.Maxr1998.modernpreferences.PreferenceScreen$Builder.build(Preferences.kt:563)
	at com.rk.xededitor.Settings.SettingsEditor.getScreen(SettingsEditor.kt:355)
	at com.rk.xededitor.Settings.SettingsEditor.onCreate(SettingsEditor.kt:44)
	at android.app.Activity.performCreate(Activity.java:8071)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
	... 11 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main' Unix Time : 1728095082077 LocalTime : 4/10/2024 21:24:42
> 
> ACTIVE_CODENAMES = [] app_version = 2.7.3 device_model = moto e32 SECURITY_PATCH = 2024-02-05 BASE_OS = motorola/hawaii/hawaii:11/ROR31.335-58/c1989:user/release-keys RELEASE = 11 CODENAME = REL manufacturer = motorola RELEASE_OR_CODENAME = 11 SDK_INT = 30 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 30 brand = motorola supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = 612c2
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean Error StackTrace :
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7955) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345) at de.Maxr1998.modernpreferences.Preference.getBoolean(Preferences.kt:321) at de.Maxr1998.modernpreferences.preferences.TwoStatePreference.onAttach$libsettings_release(TwoStatePreference.kt:58) at de.Maxr1998.modernpreferences.Preference.attachToScreen$libsettings_release(Preferences.kt:166) at de.Maxr1998.modernpreferences.PreferenceScreen.(Preferences.kt:433) at de.Maxr1998.modernpreferences.PreferenceScreen.(Unknown Source:0) at de.Maxr1998.modernpreferences.PreferenceScreen$Builder.build(Preferences.kt:563) at com.rk.xededitor.Settings.SettingsEditor.getScreen(SettingsEditor.kt:355) at com.rk.xededitor.Settings.SettingsEditor.onCreate(SettingsEditor.kt:44) at android.app.Activity.performCreate(Activity.java:8071) at android.app.Activity.performCreate(Activity.java:8054) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472) ... 11 more

Clear app data to fix it
