### ISSUE TITLE
Crash ReportTest

### ISSUE THREAD

**Issue by hasanelfalakiy** [RohitKushvaha01/Xed-Editor#34]
Crash at 1720963485987(timestamp) in thread named 'main'
Local date and time:14 Jul 2024 20.24.45

----------------------------------------
ACTIVE_CODENAMES = []
app_version = 2.2.0
device_model = vivo 1901
SECURITY_PATCH = 2022-05-01
BASE_OS = 
RELEASE = 11
CODENAME = REL
manufacturer = vivo
RELEASE_OR_CODENAME = 11
SDK_INT = 30
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 30
brand = vivo
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = eng.compil.20240513.161046
----------------------------------------

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:avisualcodespace/main.kt flg=0x43 }} to activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5370)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5411)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
	at com.rk.xededitor.MainActivity.MainActivity.newEditor(Unknown Source:51)
	at com.rk.xededitor.MainActivity.MainActivity.onActivityResult(Unknown Source:47)
	at android.app.Activity.dispatchActivityResult(Activity.java:8429)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5363)
	... 11 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
	at com.rk.xededitor.MainActivity.MainActivity.newEditor(Unknown Source:51)
	at com.rk.xededitor.MainActivity.MainActivity.onActivityResult(Unknown Source:47)
	at android.app.Activity.dispatchActivityResult(Activity.java:8429)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5363)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5411)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by RohitKushvaha01** [comment]
> Crash at 1720963485987(timestamp) in thread named 'main'
> Local date and time:14 Jul 2024 20.24.45
> 
> 
> 
> ----------------------------------------
> ACTIVE_CODENAMES = []
> app_version = 2.2.0
> device_model = vivo 1901
> SECURITY_PATCH = 2022-05-01
> BASE_OS = 
> RELEASE = 11
> CODENAME = REL
> manufacturer = vivo
> RELEASE_OR_CODENAME = 11
> SDK_INT = 30
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 30
> brand = vivo
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = eng.compil.20240513.161046
> ----------------------------------------
> 
> 
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:avisualcodespace/main.kt flg=0x43 }} to activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5370)
> 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5411)
> 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:257)
> 	at android.app.ActivityThread.main(ActivityThread.java:8192)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
> 	at com.rk.xededitor.MainActivity.MainActivity.newEditor(Unknown Source:51)
> 	at com.rk.xededitor.MainActivity.MainActivity.onActivityResult(Unknown Source:47)
> 	at android.app.Activity.dispatchActivityResult(Activity.java:8429)
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5363)
> 	... 11 more
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
> 	at com.rk.xededitor.MainActivity.MainActivity.newEditor(Unknown Source:51)
> 	at com.rk.xededitor.MainActivity.MainActivity.onActivityResult(Unknown Source:47)
> 	at android.app.Activity.dispatchActivityResult(Activity.java:8429)
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5363)
> 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5411)
> 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:257)
> 	at android.app.ActivityThread.main(ActivityThread.java:8192)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
> 
> 

Any context? How to reproduce this?

**Comment by hasanelfalakiy** [comment]
it crashed when I tried to open the .kt file, but I just tried again and it didn't

**Comment by RohitKushvaha01** [comment]
fixed
