### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Kadawe512** [RohitKushvaha01/Xed-Editor#40]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1721626431806
LocalTime : 22‏/07‏/2024 8:33:51 ص

ACTIVE_CODENAMES = []
app_version = 2.2.1
device_model = 2201117SG
SECURITY_PATCH = 2024-06-01
BASE_OS = 
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V816.0.2.0.TKEMIXM

Error Message : Failure from system
Error Cause : android.os.TransactionTooLargeException: data parcel size 9979004 bytes
Error StackTrace : 

java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1861)
	at android.app.Activity.startActivityForResult(Activity.java:5663)
	at android.app.Activity.startActivityForResult(Activity.java:5616)
	at android.app.Activity.startActivity(Activity.java:6134)
	at android.app.Activity.startActivity(Activity.java:6101)
	at io.github.rosemoe.sora.widget.component.EditorTextActionWindow.onClick(Unknown Source:194)
	at android.view.View.performClick(View.java:7592)
	at android.view.View.performClickInternal(View.java:7565)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29945)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8348)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.os.TransactionTooLargeException: data parcel size 9979004 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:643)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2638)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1854)
	... 17 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1721626431806
> LocalTime : 22‏/07‏/2024 8:33:51 ص
> 
> ACTIVE_CODENAMES = []
> app_version = 2.2.1
> device_model = 2201117SG
> SECURITY_PATCH = 2024-06-01
> BASE_OS = 
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> brand = Redmi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V816.0.2.0.TKEMIXM
> 
> 
> Error Message : Failure from system
> Error Cause : android.os.TransactionTooLargeException: data parcel size 9979004 bytes
> Error StackTrace : 
> 
> java.lang.RuntimeException: Failure from system
> 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1861)
> 	at android.app.Activity.startActivityForResult(Activity.java:5663)
> 	at android.app.Activity.startActivityForResult(Activity.java:5616)
> 	at android.app.Activity.startActivity(Activity.java:6134)
> 	at android.app.Activity.startActivity(Activity.java:6101)
> 	at io.github.rosemoe.sora.widget.component.EditorTextActionWindow.onClick(Unknown Source:194)
> 	at android.view.View.performClick(View.java:7592)
> 	at android.view.View.performClickInternal(View.java:7565)
> 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
> 	at android.view.View$PerformClick.run(View.java:29945)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:211)
> 	at android.os.Looper.loop(Looper.java:300)
> 	at android.app.ActivityThread.main(ActivityThread.java:8348)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
> Caused by: android.os.TransactionTooLargeException: data parcel size 9979004 bytes
> 	at android.os.BinderProxy.transactNative(Native Method)
> 	at android.os.BinderProxy.transact(BinderProxy.java:643)
> 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2638)
> 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1854)
> 	... 17 more
> 

How did this error occurred
