### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MuhammadBayiz** [RohitKushvaha01/Xed-Editor#41]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1721725925166
LocalTime : Jul 23, 2024 12:12:05

ACTIVE_CODENAMES = []
app_version = 2.4.2
device_model = Mi 9T
SECURITY_PATCH = 2024-06-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = eng.celest.20240628.193921

Error Message : Unable to find explicit activity class {com.rk.xededitor/com.rk.xededitor.Settings.SettingsBaseActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
Error Cause : null
Error StackTrace : 

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.rk.xededitor/com.rk.xededitor.Settings.SettingsBaseActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2430)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2008)
	at android.app.Activity.startActivityForResult(Activity.java:5840)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5798)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:6295)
	at android.app.Activity.startActivity(Activity.java:6262)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onOptionsItemSelected(Unknown Source:26)
	at android.app.Activity.onMenuItemSelected(Activity.java:4658)
	at androidx.activity.ComponentActivity.onMenuItemSelected(Unknown Source:5)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected$androidx$fragment$app$FragmentActivity(Unknown Source:0)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(Unknown Source:0)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onMenuItemSelected(Unknown Source:2)
	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(Unknown Source:66)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(Unknown Source:28)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(Unknown Source:40)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1273)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3286)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4264)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4005)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(Unknown Source:37)
	at android.view.View.performOnTouchCallback(View.java:16265)
	at android.view.View.dispatchTouchEvent(View.java:16222)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2792)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2569)
	at android.view.View.dispatchPointerEvent(View.java:16547)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7564)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7326)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6723)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6912)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6969)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9832)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9783)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9752)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9974)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by RohitKushvaha01** [comment]
try this debug build and see if it fix the issue  https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10056687116#artifacts

**Comment by MuhammadBayiz** [comment]
Now I'm getting this:
Fatal Crash occurred on Thread named 'main'
Unix Time : 1721730354139
LocalTime : Jul 23, 2024 13:25:54

ACTIVE_CODENAMES = []
app_version = 2.4.3
device_model = Mi 9T
SECURITY_PATCH = 2024-06-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = eng.celest.20240628.193921


Error Message : Unable to instantiate activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsBaseActivity}: java.lang.InstantiationException: java.lang.Class<com.rk.xededitor.Settings.SettingsBaseActivity> cannot be instantiated
Error Cause : java.lang.InstantiationException: java.lang.Class<com.rk.xededitor.Settings.SettingsBaseActivity> cannot be instantiated
Error StackTrace : 

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsBaseActivity}: java.lang.InstantiationException: java.lang.Class<com.rk.xededitor.Settings.SettingsBaseActivity> cannot be instantiated
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3899)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.InstantiationException: java.lang.Class<com.rk.xededitor.Settings.SettingsBaseActivity> cannot be instantiated
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:44)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1451)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3886)
	... 13 more

**Comment by MuhammadBayiz** [comment]
This crash happens when i open a text file inside file manager with xed-editor and inside the xed-editor i try to open settings

**Comment by RohitKushvaha01** [comment]
> This crash happens when i open a text file inside file manager with xed-editor and inside the xed-editor i try to open settings

Fixed 

https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10059354167#artifacts

**Comment by MuhammadBayiz** [comment]
Thanks
