### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by pidjan** [RohitKushvaha01/Xed-Editor#51]
dev build, when turning on plugins
Fatal Crash occurred on Thread named 'main'
Unix Time : 1721939825380
LocalTime : 25 июл. 2024 г. 23:37:05

ACTIVE_CODENAMES = []
app_version = 2.4.3
device_model = SM-G991B
SEM_INT = 3401
SECURITY_PATCH = 2024-05-01
BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys
SEM_FIRST_SDK_INT = 30
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = G991BXXSBGXDH

Error Message : View=DecorView@f129e2a[SettingsApp] not attached to window manager
Error Cause : null
Error StackTrace : 

java.lang.IllegalArgumentException: View=DecorView@f129e2a[SettingsApp] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:729)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:626)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
	at android.app.Dialog.dismissDialog(Dialog.java:801)
	at android.app.Dialog.dismiss(Dialog.java:783)
	at androidx.appcompat.app.AppCompatDialog.dismiss(AppCompatDialog.java:154)
	at com.rk.xededitor.LoadingPopup.hide$lambda$4(LoadingPopup.kt:41)
	at com.rk.xededitor.LoadingPopup.$r8$lambda$oq9YSbhp-RBvTiJq-PdY6SlLf20(Unknown Source:0)
	at com.rk.xededitor.LoadingPopup$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.app.Activity.runOnUiThread(Activity.java:7865)
	at com.rk.xededitor.LoadingPopup.hide(LoadingPopup.kt:39)
	at com.rk.xededitor.LoadingPopup.lambda$2$lambda$1$lambda$0(LoadingPopup.kt:24)
	at com.rk.xededitor.LoadingPopup$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by RohitKushvaha01** [comment]
> dev build, when turning on plugins Fatal Crash occurred on Thread named 'main' Unix Time : 1721939825380 LocalTime : 25 июл. 2024 г. 23:37:05
> 
> ACTIVE_CODENAMES = [] app_version = 2.4.3 device_model = SM-G991B SEM_INT = 3401 SECURITY_PATCH = 2024-05-01 BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys SEM_FIRST_SDK_INT = 30 RELEASE = 14 MEDIA_PERFORMANCE_CLASS = 0 CODENAME = REL manufacturer = samsung RELEASE_OR_CODENAME = 14 RELEASE_OR_PREVIEW_DISPLAY = 14 KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair} SDK_INT = 34 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 34 SEM_PLATFORM_INT = 150100 brand = samsung supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = G991BXXSBGXDH
> 
> Error Message : View=DecorView@f129e2a[SettingsApp] not attached to window manager Error Cause : null Error StackTrace :
> 
> java.lang.IllegalArgumentException: View=DecorView@f129e2a[SettingsApp] not attached to window manager at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:729) at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:626) at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208) at android.app.Dialog.dismissDialog(Dialog.java:801) at android.app.Dialog.dismiss(Dialog.java:783) at androidx.appcompat.app.AppCompatDialog.dismiss(AppCompatDialog.java:154) at com.rk.xededitor.LoadingPopup.hide$lambda$4(LoadingPopup.kt:41) at com.rk.xededitor.LoadingPopup.$r8$lambda$oq9YSbhp-RBvTiJq-PdY6SlLf20(Unknown Source:0) at com.rk.xededitor.LoadingPopup$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) at android.app.Activity.runOnUiThread(Activity.java:7865) at com.rk.xededitor.LoadingPopup.hide(LoadingPopup.kt:39) at com.rk.xededitor.LoadingPopup.lambda$2$lambda$1$lambda$0(LoadingPopup.kt:24) at com.rk.xededitor.LoadingPopup$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:230) at android.os.Looper.loop(Looper.java:319) at android.app.ActivityThread.main(ActivityThread.java:8919) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

try latest build see if its fixed

**Comment by pidjan** [comment]
works!
