### ISSUE TITLE
extra keys are not showing properly

### ISSUE THREAD

**Issue by pidjan** [RohitKushvaha01/Xed-Editor#64]
**Describe the bug**
extra keys are cropped in vertical mode, while editing when you change from vertical mode to horizontal mode - it crashes. (crashlog provided) also, in horizontal mode it is "almost" impossible to see editor text. screenshots are provided. when you try to create file with the same name as folder, it throws error and infinite loading screen appears saying "please wait".

crashlog:
```
Fatal Crash occurred on Thread named 'main'
Unix Time : 1722264458317
LocalTime : 29 июл. 2024 г. 17:47:38

ACTIVE_CODENAMES = []
app_version = 2.5.0
device_model = SM-G991B
SEM_INT = 3401
SECURITY_PATCH = 2024-05-01
BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys
SEM_FIRST_SDK_INT = 30
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = G991BXXSBGXDH


Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
Error Cause : java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
Error StackTrace : 

java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6149)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6181)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6471)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6378)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.rk.xededitor.MainActivity.mAdapter.getCount(mAdapter.java:45)
	at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.canScroll(ViewPager.java:3087)
	at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityEvent(ViewPager.java:3043)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:78)
	at android.view.View.onInitializeAccessibilityEvent(View.java:9184)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:8998)
	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:33242)
	at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:197)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:115)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:8975)
	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:13221)
	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.removeCallbacksAndRun(ViewRootImpl.java:13294)
	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:13286)
	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:11862)
	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:12050)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
	at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:15518)
	at android.view.ViewGroup.notifySubtreeAccessibilityStateChangedIfNeeded(ViewGroup.java:4106)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5872)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5815)
	at android.view.ViewGroup.removeView(ViewGroup.java:5746)
	at androidx.viewpager.widget.ViewPager.removeView(ViewPager.java:1507)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.kt:398)
	at androidx.fragment.app.SpecialEffectsController.enqueue$lambda$4$lambda$2(SpecialEffectsController.kt:147)
	at androidx.fragment.app.SpecialEffectsController.$r8$lambda$TeCmoVW0hctjg0BNHLP6mPbAs5U(Unknown Source:0)
	at androidx.fragment.app.SpecialEffectsController$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.kt:608)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:663)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.kt:507)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.kt:293)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3037)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:258)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
	at com.rk.xededitor.MainActivity.MainActivity.onDestroy(MainActivity.java:363)
	at android.app.Activity.performDestroy(Activity.java:9274)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1491)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6136)
	... 15 more

```
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240729_175105_Karbon](https://github.com/user-attachments/assets/8ff19880-b5db-4068-b692-5d0fab6bcc80)
![Screenshot_20240729_175118_Karbon](https://github.com/user-attachments/assets/b1568ca4-66a0-4c4f-b7e1-c5011f2dcdd7)
![Screenshot_20240729_175125_Karbon](https://github.com/user-attachments/assets/6f5c186f-e080-462e-83c9-05027e77e947)
![Screenshot_20240729_180346_Karbon](https://github.com/user-attachments/assets/932cb965-031e-4131-aef9-f34d33dc5816)

**complete the following information):**
 - Device: Galaxy S21 5G
 - OS: One UI 6.1
 - Android Version: Android 14

**logcat output/logcat.txt(if applicable)**

**Additional context**

**Comment by pidjan** [comment]
![Screenshot_20240729_180343_Karbon](https://github.com/user-attachments/assets/09d291e4-39f7-4dcb-a74d-a023ae3b8784)

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> extra keys are cropped in vertical mode, while editing when you change from vertical mode to horizontal mode - it crashes. (crashlog provided) also, in horizontal mode it is "almost" impossible to see editor text. screenshots are provided. when you try to create file with the same name as folder, it throws error and infinite loading screen appears saying "please wait".
> 
> crashlog:
> ```
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1722264458317
> LocalTime : 29 июл. 2024 г. 17:47:38
> 
> ACTIVE_CODENAMES = []
> app_version = 2.5.0
> device_model = SM-G991B
> SEM_INT = 3401
> SECURITY_PATCH = 2024-05-01
> BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys
> SEM_FIRST_SDK_INT = 30
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> SEM_PLATFORM_INT = 150100
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = G991BXXSBGXDH
> 
> 
> Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
> Error Cause : java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6149)
> 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6181)
> 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6471)
> 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6378)
> 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
> 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:230)
> 	at android.os.Looper.loop(Looper.java:319)
> 	at android.app.ActivityThread.main(ActivityThread.java:8919)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
> 	at com.rk.xededitor.MainActivity.mAdapter.getCount(mAdapter.java:45)
> 	at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.canScroll(ViewPager.java:3087)
> 	at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityEvent(ViewPager.java:3043)
> 	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:78)
> 	at android.view.View.onInitializeAccessibilityEvent(View.java:9184)
> 	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:8998)
> 	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:33242)
> 	at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:197)
> 	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:115)
> 	at android.view.View.sendAccessibilityEventUnchecked(View.java:8975)
> 	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:13221)
> 	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.removeCallbacksAndRun(ViewRootImpl.java:13294)
> 	at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:13286)
> 	at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:11862)
> 	at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:12050)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:4082)
> 	at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:15518)
> 	at android.view.ViewGroup.notifySubtreeAccessibilityStateChangedIfNeeded(ViewGroup.java:4106)
> 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5872)
> 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5815)
> 	at android.view.ViewGroup.removeView(ViewGroup.java:5746)
> 	at androidx.viewpager.widget.ViewPager.removeView(ViewPager.java:1507)
> 	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.kt:398)
> 	at androidx.fragment.app.SpecialEffectsController.enqueue$lambda$4$lambda$2(SpecialEffectsController.kt:147)
> 	at androidx.fragment.app.SpecialEffectsController.$r8$lambda$TeCmoVW0hctjg0BNHLP6mPbAs5U(Unknown Source:0)
> 	at androidx.fragment.app.SpecialEffectsController$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.kt:608)
> 	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:663)
> 	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.kt:507)
> 	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.kt:293)
> 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3037)
> 	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
> 	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
> 	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:258)
> 	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
> 	at com.rk.xededitor.MainActivity.MainActivity.onDestroy(MainActivity.java:363)
> 	at android.app.Activity.performDestroy(Activity.java:9274)
> 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1491)
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6136)
> 	... 15 more
> 
> ```
> **To Reproduce**
> 
> 
> **Expected behavior**
> 
> 
> **Screenshots**
> ![Screenshot_20240729_175105_Karbon](https://github.com/user-attachments/assets/8ff19880-b5db-4068-b692-5d0fab6bcc80)
> ![Screenshot_20240729_175118_Karbon](https://github.com/user-attachments/assets/b1568ca4-66a0-4c4f-b7e1-c5011f2dcdd7)
> ![Screenshot_20240729_175125_Karbon](https://github.com/user-attachments/assets/6f5c186f-e080-462e-83c9-05027e77e947)
> ![Screenshot_20240729_180346_Karbon](https://github.com/user-attachments/assets/932cb965-031e-4131-aef9-f34d33dc5816)
> 
> 
> **complete the following information):**
>  - Device: Galaxy S21 5G
>  - OS: One UI 6.1
>  - Android Version: Android 14
> 
> **logcat output/logcat.txt(if applicable)**
> 
> 
> **Additional context**
> 

Horizontal keyboard is a issue I think I should just disable the keyboard when the app is in horizontal mode?

**Comment by pidjan** [comment]
> Horizontal keyboard is a issue I think I should just disable the keyboard when the app is in horizontal mode?
idk. do what you think is better.
