### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Caboaros** [RohitKushvaha01/Xed-Editor#72]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1722913914289
LocalTime : 6 de ago. de 2024 00:11:54

ACTIVE_CODENAMES = []
app_version = 2.3.0
device_model = 2201117TG
SECURITY_PATCH = 2024-06-01
BASE_OS = 
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V816.0.5.0.TGCMIXM

Error Message : Can't change tag of fragment DynamicFragment{6e813fa} (0197295e-d724-4554-a20f-9f19105dab3d id=0x7f090253 tag=android:switcher:2131296851:1): was android:switcher:2131296851:1 now android:switcher:2131296851:0
Error Cause : null
Error StackTrace : 

java.lang.IllegalStateException: Can't change tag of fragment DynamicFragment{6e813fa} (0197295e-d724-4554-a20f-9f19105dab3d id=0x7f090253 tag=android:switcher:2131296851:1): was android:switcher:2131296851:1 now android:switcher:2131296851:0
	at androidx.fragment.app.BackStackRecord.doAddOp(Unknown Source:86)
	at androidx.viewpager.widget.ViewPager.addNewItem(Unknown Source:113)
	at androidx.viewpager.widget.ViewPager.populate(SourceFile:18)
	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(Unknown Source:116)
	at androidx.viewpager.widget.ViewPager.dataSetChanged(Unknown Source:177)
	at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(Unknown Source:44)
	at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(Unknown Source:5)
	at io.github.rosemoe.sora.text.ContentIO$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:70)
	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(Unknown Source:86)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(Unknown Source:28)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(Unknown Source:40)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1231)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3258)
	at android.widget.AbsListView$3.run(AbsListView.java:4264)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1722913914289
> LocalTime : 6 de ago. de 2024 00:11:54
> 
> ACTIVE_CODENAMES = []
> app_version = 2.3.0
> device_model = 2201117TG
> SECURITY_PATCH = 2024-06-01
> BASE_OS = 
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> brand = Redmi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V816.0.5.0.TGCMIXM
> 
> 
> Error Message : Can't change tag of fragment DynamicFragment{6e813fa} (0197295e-d724-4554-a20f-9f19105dab3d id=0x7f090253 tag=android:switcher:2131296851:1): was android:switcher:2131296851:1 now android:switcher:2131296851:0
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.IllegalStateException: Can't change tag of fragment DynamicFragment{6e813fa} (0197295e-d724-4554-a20f-9f19105dab3d id=0x7f090253 tag=android:switcher:2131296851:1): was android:switcher:2131296851:1 now android:switcher:2131296851:0
> 	at androidx.fragment.app.BackStackRecord.doAddOp(Unknown Source:86)
> 	at androidx.viewpager.widget.ViewPager.addNewItem(Unknown Source:113)
> 	at androidx.viewpager.widget.ViewPager.populate(SourceFile:18)
> 	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(Unknown Source:116)
> 	at androidx.viewpager.widget.ViewPager.dataSetChanged(Unknown Source:177)
> 	at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(Unknown Source:44)
> 	at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(Unknown Source:5)
> 	at io.github.rosemoe.sora.text.ContentIO$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:70)
> 	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(Unknown Source:86)
> 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
> 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(Unknown Source:28)
> 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(Unknown Source:40)
> 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
> 	at android.widget.AbsListView.performItemClick(AbsListView.java:1231)
> 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3258)
> 	at android.widget.AbsListView$3.run(AbsListView.java:4264)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:211)
> 	at android.os.Looper.loop(Looper.java:300)
> 	at android.app.ActivityThread.main(ActivityThread.java:8503)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
> 

You are using old version of xed/Karbon please use a release build from GitHub or latest build from GitHub actions
