### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BlackNinja218** [RohitKushvaha01/Xed-Editor#85]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1723959576335
LocalTime : Aug 18, 2024 12:39:36 AM

ACTIVE_CODENAMES = []
app_version = 2.4.2
device_model = SM-F946U
SEM_INT = 3401
SECURITY_PATCH = 2024-08-01
BASE_OS = samsung/q5qsqw/q5q:14/UP1A.231005.007/F946USQU2CXCF:user/release-keys
SEM_FIRST_SDK_INT = 33
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = F946USQS4CXG6

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092
Error Cause : java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6379)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:8023)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3857)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1528)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(Unknown Source:476)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	... 12 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main' Unix Time : 1723959576335 LocalTime : Aug 18, 2024 12:39:36 AM
> 
> ACTIVE_CODENAMES = [] app_version = 2.4.2 device_model = SM-F946U SEM_INT = 3401 SECURITY_PATCH = 2024-08-01 BASE_OS = samsung/q5qsqw/q5q:14/UP1A.231005.007/F946USQU2CXCF:user/release-keys SEM_FIRST_SDK_INT = 33 RELEASE = 14 MEDIA_PERFORMANCE_CLASS = 0 CODENAME = REL manufacturer = samsung RELEASE_OR_CODENAME = 14 RELEASE_OR_PREVIEW_DISPLAY = 14 KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair} SDK_INT = 34 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 34 SEM_PLATFORM_INT = 150100 brand = samsung supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = F946USQS4CXG6
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092 Error Cause : java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092 Error StackTrace :
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:230) at android.os.Looper.loop(Looper.java:319) at android.app.ActivityThread.main(ActivityThread.java:8919) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) Caused by: java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{dbc274b 13028:com.rk.xededitor/u0a292} (pid=13028, uid=10292) that is not exported from UID 11092 at android.os.Parcel.createExceptionOrNull(Parcel.java:3069) at android.os.Parcel.createException(Parcel.java:3053) at android.os.Parcel.readException(Parcel.java:3036) at android.os.Parcel.readException(Parcel.java:2978) at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6379) at android.app.ActivityThread.acquireProvider(ActivityThread.java:8023) at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3857) at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542) at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027) at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858) at android.content.ContentResolver.openInputStream(ContentResolver.java:1528) at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(Unknown Source:476) at android.app.Activity.performCreate(Activity.java:8975) at android.app.Activity.performCreate(Activity.java:8944) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146) ... 12 more

@BlackNinja218 you are using a older version of karbon/xed-editor, use v2.6.0 or later
