### ISSUE TITLE
Crash Report: open file from tree

### ISSUE THREAD

**Issue by AndroMaster436** [RohitKushvaha01/Xed-Editor#89]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1724055119629
LocalTime : 19 авг. 2024 г. 11:11:59

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = Redmi 10
SECURITY_PATCH = 2021-12-05
BASE_OS = 
RELEASE = 11
CODENAME = REL
manufacturer = xiaomi
RELEASE_OR_CODENAME = 11
SDK_INT = 30
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 30
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 1640821528

Error Message : java.lang.String cannot be cast to java.lang.Boolean
Error Cause : null
Error StackTrace : 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:54)
	at com.rk.xededitor.MainActivity.MainActivity$Companion.updateMenuItems(MainActivity.kt:436)
	at com.rk.xededitor.MainActivity.MainActivity.newEditor(MainActivity.kt:262)
	at com.rk.xededitor.MainActivity.MainActivity.newEditor$default(MainActivity.kt:238)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1.onItemClick$lambda$2$lambda$1(TreeView.kt:41)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1.$r8$lambda$isyZ-xwGLbfRv25Z5KwrHGjsc7o(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main' Unix Time : 1724055119629 LocalTime : 19 авг. 2024 г. 11:11:59
> 
> ACTIVE_CODENAMES = [] app_version = 2.6.0 device_model = Redmi 10 SECURITY_PATCH = 2021-12-05 BASE_OS = RELEASE = 11 CODENAME = REL manufacturer = xiaomi RELEASE_OR_CODENAME = 11 SDK_INT = 30 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 30 brand = Redmi supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = 1640821528
> 
> Error Message : java.lang.String cannot be cast to java.lang.Boolean Error Cause : null Error StackTrace :
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345) at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:54) at com.rk.xededitor.MainActivity.MainActivity$Companion.updateMenuItems(MainActivity.kt:436) at com.rk.xededitor.MainActivity.MainActivity.newEditor(MainActivity.kt:262) at com.rk.xededitor.MainActivity.MainActivity.newEditor$default(MainActivity.kt:238) at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1.onItemClick$lambda$2$lambda$1(TreeView.kt:41) at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1.$r8$lambda$isyZ-xwGLbfRv25Z5KwrHGjsc7o(Unknown Source:0) at com.rk.xededitor.MainActivity.treeview2.TreeView$1$1$1$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7664) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

have you tried clearing app data because of the Settings class is refactored
