### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jujubeja** [RohitKushvaha01/Xed-Editor#99]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1724592049713
LocalTime : Aug 25, 2024 9:20:49 PM

ALL_CODENAMES = [REL]
ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = Pixel 7
MIN_SUPPORTED_TARGET_SDK_INT = 28
RESOURCES_SDK_INT = 34
SECURITY_PATCH = 2024-08-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 33
CODENAME = REL
manufacturer = Google
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
DEVICE_INITIAL_SDK_INT = 33
PREVIEW_SDK_INT = 0
SDK = 34
brand = google
supported_abi = [arm64-v8a]
INCREMENTAL = 2024082200

Error Message : Failed to allocate a 78257832 byte allocation with 65812752 free bytes and 62MB until OOM, target footprint 268435456, growth limit 268435456
Error Cause : null
Error StackTrace : 

java.lang.OutOfMemoryError: Failed to allocate a 78257832 byte allocation with 65812752 free bytes and 62MB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
	at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233)
	at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1685)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:692)
	at java.lang.StringBuilder.append(StringBuilder.java:242)
	at io.github.rosemoe.sora.text.ContentLine.appendTo(ContentLine.java:304)
	at io.github.rosemoe.sora.text.Content.appendToStringBuilder(Content.java:979)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:951)
	at io.github.rosemoe.sora.widget.CodeEditor.createAccessibilityNodeInfo(CodeEditor.java:4467)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1526)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1549)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1315)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:405)
	at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1719)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main' Unix Time : 1724592049713 LocalTime : Aug 25, 2024 9:20:49 PM
> 
> ALL_CODENAMES = [REL] ACTIVE_CODENAMES = [] app_version = 2.6.0 device_model = Pixel 7 MIN_SUPPORTED_TARGET_SDK_INT = 28 RESOURCES_SDK_INT = 34 SECURITY_PATCH = 2024-08-05 BASE_OS = RELEASE = 14 MEDIA_PERFORMANCE_CLASS = 33 CODENAME = REL manufacturer = Google RELEASE_OR_CODENAME = 14 RELEASE_OR_PREVIEW_DISPLAY = 14 KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair} SDK_INT = 34 PREVIEW_SDK_FINGERPRINT = REL DEVICE_INITIAL_SDK_INT = 33 PREVIEW_SDK_INT = 0 SDK = 34 brand = google supported_abi = [arm64-v8a] INCREMENTAL = 2024082200
> 
> Error Message : Failed to allocate a 78257832 byte allocation with 65812752 free bytes and 62MB until OOM, target footprint 268435456, growth limit 268435456 Error Cause : null Error StackTrace :
> 
> java.lang.OutOfMemoryError: Failed to allocate a 78257832 byte allocation with 65812752 free bytes and 62MB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50) at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233) at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1685) at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:692) at java.lang.StringBuilder.append(StringBuilder.java:242) at io.github.rosemoe.sora.text.ContentLine.appendTo(ContentLine.java:304) at io.github.rosemoe.sora.text.Content.appendToStringBuilder(Content.java:979) at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:951) at io.github.rosemoe.sora.widget.CodeEditor.createAccessibilityNodeInfo(CodeEditor.java:4467) at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1526) at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1549) at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1315) at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:405) at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0) at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1719) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loopOnce(Looper.java:232) at android.os.Looper.loop(Looper.java:317) at android.app.ActivityThread.main(ActivityThread.java:8623) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) at com.android.internal.os.ExecInit.main(ExecInit.java:50) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

try latest commit artifact
